package modelo.pojo;
// Generated 15-nov-2016 8:51:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Catalogocitologias generated by hbm2java
 */
public class Catalogocitologias  implements java.io.Serializable {


     private int idtblcatcitologias;
     private String nombre;
     private Set citologias = new HashSet(0);

    public Catalogocitologias() {
    }

	
    public Catalogocitologias(int idtblcatcitologias, String nombre) {
        this.idtblcatcitologias = idtblcatcitologias;
        this.nombre = nombre;
    }
    public Catalogocitologias(int idtblcatcitologias, String nombre, Set citologias) {
       this.idtblcatcitologias = idtblcatcitologias;
       this.nombre = nombre;
       this.citologias = citologias;
    }
   
    public int getIdtblcatcitologias() {
        return this.idtblcatcitologias;
    }
    
    public void setIdtblcatcitologias(int idtblcatcitologias) {
        this.idtblcatcitologias = idtblcatcitologias;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Set getCitologias() {
        return this.citologias;
    }
    
    public void setCitologias(Set citologias) {
        this.citologias = citologias;
    }




}


