package modelo.pojo;
// Generated 15-nov-2016 8:51:03 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Citologia generated by hbm2java
 */
public class Citologia  implements java.io.Serializable {


     private int idtblcito;
     private Camposhansa camposhansa;
     private Catalogocitologias catalogocitologias;
     private Firmasmedicos firmasmedicosByIdtblfirma2;
     private Firmasmedicos firmasmedicosByIdtblfirma1;
     private Boolean deteccioncancer;
     private Boolean indicemaduracion;
     private String otrosindices;
     private String diagnosticoclinico;
     private String fur;
     private String fup;
     private String gravidad;
     private String para;
     private Integer abortos;
     private String otros;
     private Date fechainforme;
     private Date fechamuestra;
     private String informe;
     private Set variablescitologias = new HashSet(0);

    public Citologia() {
    }

	
    public Citologia(int idtblcito, Camposhansa camposhansa) {
        this.idtblcito = idtblcito;
        this.camposhansa = camposhansa;
    }
    public Citologia(int idtblcito, Camposhansa camposhansa, Catalogocitologias catalogocitologias, Firmasmedicos firmasmedicosByIdtblfirma2, Firmasmedicos firmasmedicosByIdtblfirma1, Boolean deteccioncancer, Boolean indicemaduracion, String otrosindices, String diagnosticoclinico, String fur, String fup, String gravidad, String para, Integer abortos, String otros, Date fechainforme, Date fechamuestra, String informe, Set variablescitologias) {
       this.idtblcito = idtblcito;
       this.camposhansa = camposhansa;
       this.catalogocitologias = catalogocitologias;
       this.firmasmedicosByIdtblfirma2 = firmasmedicosByIdtblfirma2;
       this.firmasmedicosByIdtblfirma1 = firmasmedicosByIdtblfirma1;
       this.deteccioncancer = deteccioncancer;
       this.indicemaduracion = indicemaduracion;
       this.otrosindices = otrosindices;
       this.diagnosticoclinico = diagnosticoclinico;
       this.fur = fur;
       this.fup = fup;
       this.gravidad = gravidad;
       this.para = para;
       this.abortos = abortos;
       this.otros = otros;
       this.fechainforme = fechainforme;
       this.fechamuestra = fechamuestra;
       this.informe = informe;
       this.variablescitologias = variablescitologias;
    }
   
    public int getIdtblcito() {
        return this.idtblcito;
    }
    
    public void setIdtblcito(int idtblcito) {
        this.idtblcito = idtblcito;
    }
    public Camposhansa getCamposhansa() {
        return this.camposhansa;
    }
    
    public void setCamposhansa(Camposhansa camposhansa) {
        this.camposhansa = camposhansa;
    }
    public Catalogocitologias getCatalogocitologias() {
        return this.catalogocitologias;
    }
    
    public void setCatalogocitologias(Catalogocitologias catalogocitologias) {
        this.catalogocitologias = catalogocitologias;
    }
    public Firmasmedicos getFirmasmedicosByIdtblfirma2() {
        return this.firmasmedicosByIdtblfirma2;
    }
    
    public void setFirmasmedicosByIdtblfirma2(Firmasmedicos firmasmedicosByIdtblfirma2) {
        this.firmasmedicosByIdtblfirma2 = firmasmedicosByIdtblfirma2;
    }
    public Firmasmedicos getFirmasmedicosByIdtblfirma1() {
        return this.firmasmedicosByIdtblfirma1;
    }
    
    public void setFirmasmedicosByIdtblfirma1(Firmasmedicos firmasmedicosByIdtblfirma1) {
        this.firmasmedicosByIdtblfirma1 = firmasmedicosByIdtblfirma1;
    }
    public Boolean getDeteccioncancer() {
        return this.deteccioncancer;
    }
    
    public void setDeteccioncancer(Boolean deteccioncancer) {
        this.deteccioncancer = deteccioncancer;
    }
    public Boolean getIndicemaduracion() {
        return this.indicemaduracion;
    }
    
    public void setIndicemaduracion(Boolean indicemaduracion) {
        this.indicemaduracion = indicemaduracion;
    }
    public String getOtrosindices() {
        return this.otrosindices;
    }
    
    public void setOtrosindices(String otrosindices) {
        this.otrosindices = otrosindices;
    }
    public String getDiagnosticoclinico() {
        return this.diagnosticoclinico;
    }
    
    public void setDiagnosticoclinico(String diagnosticoclinico) {
        this.diagnosticoclinico = diagnosticoclinico;
    }
    public String getFur() {
        return this.fur;
    }
    
    public void setFur(String fur) {
        this.fur = fur;
    }
    public String getFup() {
        return this.fup;
    }
    
    public void setFup(String fup) {
        this.fup = fup;
    }
    public String getGravidad() {
        return this.gravidad;
    }
    
    public void setGravidad(String gravidad) {
        this.gravidad = gravidad;
    }
    public String getPara() {
        return this.para;
    }
    
    public void setPara(String para) {
        this.para = para;
    }
    public Integer getAbortos() {
        return this.abortos;
    }
    
    public void setAbortos(Integer abortos) {
        this.abortos = abortos;
    }
    public String getOtros() {
        return this.otros;
    }
    
    public void setOtros(String otros) {
        this.otros = otros;
    }
    public Date getFechainforme() {
        return this.fechainforme;
    }
    
    public void setFechainforme(Date fechainforme) {
        this.fechainforme = fechainforme;
    }
    public Date getFechamuestra() {
        return this.fechamuestra;
    }
    
    public void setFechamuestra(Date fechamuestra) {
        this.fechamuestra = fechamuestra;
    }
    public String getInforme() {
        return this.informe;
    }
    
    public void setInforme(String informe) {
        this.informe = informe;
    }
    public Set getVariablescitologias() {
        return this.variablescitologias;
    }
    
    public void setVariablescitologias(Set variablescitologias) {
        this.variablescitologias = variablescitologias;
    }




}


