package modelo.pojo;
// Generated 15-nov-2016 8:51:03 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Firmasmedicos generated by hbm2java
 */
public class Firmasmedicos  implements java.io.Serializable {


     private int idtblfirmamed;
     private String nombre;
     private String codigo;
     private Set citologiasForIdtblfirma2 = new HashSet(0);
     private Set citologiasForIdtblfirma1 = new HashSet(0);
     private Set histopatologias = new HashSet(0);

    public Firmasmedicos() {
    }

	
    public Firmasmedicos(int idtblfirmamed, String nombre, String codigo) {
        this.idtblfirmamed = idtblfirmamed;
        this.nombre = nombre;
        this.codigo = codigo;
    }
    public Firmasmedicos(int idtblfirmamed, String nombre, String codigo, Set citologiasForIdtblfirma2, Set citologiasForIdtblfirma1, Set histopatologias) {
       this.idtblfirmamed = idtblfirmamed;
       this.nombre = nombre;
       this.codigo = codigo;
       this.citologiasForIdtblfirma2 = citologiasForIdtblfirma2;
       this.citologiasForIdtblfirma1 = citologiasForIdtblfirma1;
       this.histopatologias = histopatologias;
    }
   
    public int getIdtblfirmamed() {
        return this.idtblfirmamed;
    }
    
    public void setIdtblfirmamed(int idtblfirmamed) {
        this.idtblfirmamed = idtblfirmamed;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Set getCitologiasForIdtblfirma2() {
        return this.citologiasForIdtblfirma2;
    }
    
    public void setCitologiasForIdtblfirma2(Set citologiasForIdtblfirma2) {
        this.citologiasForIdtblfirma2 = citologiasForIdtblfirma2;
    }
    public Set getCitologiasForIdtblfirma1() {
        return this.citologiasForIdtblfirma1;
    }
    
    public void setCitologiasForIdtblfirma1(Set citologiasForIdtblfirma1) {
        this.citologiasForIdtblfirma1 = citologiasForIdtblfirma1;
    }
    public Set getHistopatologias() {
        return this.histopatologias;
    }
    
    public void setHistopatologias(Set histopatologias) {
        this.histopatologias = histopatologias;
    }




}


