package modelo.pojo;
// Generated 15-nov-2016 8:51:03 by Hibernate Tools 4.3.1



/**
 * Fotoshisto generated by hbm2java
 */
public class Fotoshisto  implements java.io.Serializable {


     private int idtblfotoshisto;
     private String codigohisto;
     private String dirfoto;
     private Histopatologia histopatologia;

    public Fotoshisto() {
    }

	
    public Fotoshisto(int idtblfotoshisto, String codigohisto, String dirfoto) {
        this.idtblfotoshisto = idtblfotoshisto;
        this.codigohisto = codigohisto;
        this.dirfoto = dirfoto;
    }
    public Fotoshisto(int idtblfotoshisto, String codigohisto, String dirfoto, Histopatologia histopatologia) {
       this.idtblfotoshisto = idtblfotoshisto;
       this.codigohisto = codigohisto;
       this.dirfoto = dirfoto;
       this.histopatologia = histopatologia;
    }
   
    public int getIdtblfotoshisto() {
        return this.idtblfotoshisto;
    }
    
    public void setIdtblfotoshisto(int idtblfotoshisto) {
        this.idtblfotoshisto = idtblfotoshisto;
    }
    public String getCodigohisto() {
        return this.codigohisto;
    }
    
    public void setCodigohisto(String codigohisto) {
        this.codigohisto = codigohisto;
    }
    public String getDirfoto() {
        return this.dirfoto;
    }
    
    public void setDirfoto(String dirfoto) {
        this.dirfoto = dirfoto;
    }
    public Histopatologia getHistopatologia() {
        return this.histopatologia;
    }
    
    public void setHistopatologia(Histopatologia histopatologia) {
        this.histopatologia = histopatologia;
    }




}


